### ISSUE TITLE
"tuple index out of range" When I try to run V2

### ISSUE THREAD

**Issue by noriix** [smthemex/ComfyUI_EchoMimic#100]
When I try to run V2, I get the error “tuple index out of range"

# ComfyUI Error Report
## Error Details
- **Node ID:** 4
- **Node Type:** Echo_Sampler
- **Exception Type:** IndexError
- **Exception Message:** tuple index out of range
## Stack Trace
```
  File "G:\StabilityMatrix\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "G:\StabilityMatrix\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "G:\StabilityMatrix\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "G:\StabilityMatrix\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "G:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 448, in em_main
    output_video=process_video_v2(image, audio_file, width, height, length, seed,

  File "G:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_EchoMimic\utils.py", line 78, in process_video_v2
    re = im.shape[:2][1]

```
## System Information
- **ComfyUI Version:** v0.3.5-12-g3fc6ebc
- **Arguments:** G:\StabilityMatrix\Packages\ComfyUI\main.py --preview-method auto
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884377600
  - **VRAM Free:** 11440231442
  - **Torch VRAM Total:** 369098752
  - **Torch VRAM Free:** 45356050

## Logs
```
2024-12-01T09:27:30.591808 - Total VRAM 12288 MB, total RAM 32637 MB
2024-12-01T09:27:30.591808 - pytorch version: 2.5.1+cu124
2024-12-01T09:27:30.592806 - Set vram state to: NORMAL_VRAM
2024-12-01T09:27:30.592806 - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-12-01T09:27:31.715715 - Using pytorch cross attention
2024-12-01T09:27:32.770108 - [Prompt Server] web root: G:\StabilityMatrix\Packages\ComfyUI\web
2024-12-01T09:27:32.772108 - Adding extra search path checkpoints G:\StabilityMatrix\Models\StableDiffusion
2024-12-01T09:27:32.772108 - Adding extra search path vae G:\StabilityMatrix\Models\VAE
2024-12-01T09:27:32.772108 - Adding extra search path loras G:\StabilityMatrix\Models\Lora
2024-12-01T09:27:32.772108 - Adding extra search path loras G:\StabilityMatrix\Models\LyCORIS
2024-12-01T09:27:32.772108 - Adding extra search path upscale_models G:\StabilityMatrix\Models\ESRGAN
2024-12-01T09:27:32.772108 - Adding extra search path upscale_models G:\StabilityMatrix\Models\RealESRGAN
2024-12-01T09:27:32.772108 - Adding extra search path upscale_models G:\StabilityMatrix\Models\SwinIR
2024-12-01T09:27:32.772108 - Adding extra search path embeddings G:\StabilityMatrix\Models\TextualInversion
2024-12-01T09:27:32.772108 - Adding extra search path hypernetworks G:\StabilityMatrix\Models\Hypernetwork
2024-12-01T09:27:32.772108 - Adding extra search path controlnet G:\StabilityMatrix\Models\ControlNet
2024-12-01T09:27:32.772108 - Adding extra search path controlnet G:\StabilityMatrix\Models\T2IAdapter
2024-12-01T09:27:32.772108 - Adding extra search path clip G:\StabilityMatrix\Models\CLIP
2024-12-01T09:27:32.772108 - Adding extra search path clip_vision G:\StabilityMatrix\Models\InvokeClipVision
2024-12-01T09:27:32.772108 - Adding extra search path diffusers G:\StabilityMatrix\Models\Diffusers
2024-12-01T09:27:32.772108 - Adding extra search path gligen G:\StabilityMatrix\Models\GLIGEN
2024-12-01T09:27:32.772108 - Adding extra search path vae_approx G:\StabilityMatrix\Models\ApproxVAE
2024-12-01T09:27:32.772108 - Adding extra search path ipadapter G:\StabilityMatrix\Models\IpAdapter
2024-12-01T09:27:32.773108 - Adding extra search path ipadapter G:\StabilityMatrix\Models\InvokeIpAdapters15
2024-12-01T09:27:32.773108 - Adding extra search path ipadapter G:\StabilityMatrix\Models\InvokeIpAdaptersXl
2024-12-01T09:27:32.773108 - Adding extra search path prompt_expansion G:\StabilityMatrix\Models\PromptExpansion
2024-12-01T09:27:32.773108 - Adding extra search path ultralytics G:\StabilityMatrix\Models\Ultralytics
2024-12-01T09:27:32.773108 - Adding extra search path ultralytics_bbox G:\StabilityMatrix\Models\Ultralytics\bbox
2024-12-01T09:27:32.773108 - Adding extra search path ultralytics_segm G:\StabilityMatrix\Models\Ultralytics\segm
2024-12-01T09:27:32.773108 - Adding extra search path sams G:\StabilityMatrix\Models\Sams
2024-12-01T09:27:32.773108 - Adding extra search path diffusion_models G:\StabilityMatrix\Models\unet
2024-12-01T09:27:34.834116 - 
Import times for custom nodes:
2024-12-01T09:27:34.834116 -    0.0 seconds: G:\StabilityMatrix\Packages\ComfyUI\custom_nodes\websocket_image_save.py
2024-12-01T09:27:34.834116 -    0.2 seconds: G:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-12-01T09:27:34.834116 -    1.3 seconds: G:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_EchoMimic
2024-12-01T09:27:34.834116 - 
2024-12-01T09:27:34.839207 - Starting server

2024-12-01T09:27:34.839207 - To see the GUI go to: http://127.0.0.1:8188
2024-12-01T09:27:55.635615 - got prompt
2024-12-01T09:27:55.933612 - ****** refer in EchoMimic V2 mode!******
2024-12-01T09:27:55.934613 - G:\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\diffusers\configuration_utils.py:245: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a model, please use <class 'ComfyUI_EchoMimic.echomimic_v2.src.models.unet_2d_condition.UNet2DConditionModel'>.load_config(...) followed by <class 'ComfyUI_EchoMimic.echomimic_v2.src.models.unet_2d_condition.UNet2DConditionModel'>.from_config(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)
2024-12-01T09:27:55.964612 - G:\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\diffusers\models\lora.py:306: FutureWarning: `LoRACompatibleConv` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleConv` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleConv", "1.0.0", deprecation_message)
2024-12-01T09:27:59.684942 - G:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py:234: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  re_state = torch.load(re_ckpt, map_location="cpu")
2024-12-01T09:28:00.488520 - loaded temporal unet's pretrained weights from G:\StabilityMatrix\Packages\ComfyUI\models\echo_mimic\unet ...
2024-12-01T09:28:10.706676 - Load motion module params from G:\StabilityMatrix\Packages\ComfyUI\models\echo_mimic\v2\motion_module.pth
2024-12-01T09:28:16.797278 - Loaded 453.20928M-parameter motion module
2024-12-01T09:28:17.280688 - G:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py:280: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  denoising_state = torch.load(denois_pt, map_location="cpu")
2024-12-01T09:28:28.622808 - G:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py:307: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  pose_state = torch.load(pose_encoder_pt)
2024-12-01T09:28:32.336804 - G:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\__init__.py:109: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)
2024-12-01T09:28:33.242806 - when use echo v2,need choice a pose dir,for get error using default pose !
2024-12-01T09:28:33.377805 - ***** infer length is 1202024-12-01T09:28:33.377805 - 
2024-12-01T09:28:33.382804 - !!! Exception during processing !!! tuple index out of range
2024-12-01T09:28:33.383804 - Traceback (most recent call last):
  File "G:\StabilityMatrix\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\StabilityMatrix\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\StabilityMatrix\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\StabilityMatrix\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "G:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 448, in em_main
    output_video=process_video_v2(image, audio_file, width, height, length, seed,
  File "G:\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI_EchoMimic\utils.py", line 78, in process_video_v2
    re = im.shape[:2][1]
IndexError: tuple index out of range

2024-12-01T09:28:33.384805 - Prompt executed in 37.70 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":5,"last_link_id":8,"nodes":[{"id":1,"type":"LoadAudio","pos":[230,330],"size":[315,124],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"AUDIO","type":"AUDIO","links":[4],"slot_index":0}],"properties":{"Node name for S&R":"LoadAudio"},"widgets_values":["sample.wav",null,""]},{"id":5,"type":"VHS_VideoCombine","pos":[1020,120],"size":[270,570],"flags":{},"order":4,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":6},{"name":"audio","type":"AUDIO","link":7,"shape":7},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7},{"name":"vae","type":"VAE","link":null,"shape":7},{"name":"frame_rate","type":"FLOAT","link":8,"widget":{"name":"frame_rate"}}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"slot_index":0}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":8,"loop_count":0,"filename_prefix":"AnimateDiff","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"AnimateDiff_00005-audio.mp4","subfolder":"","type":"output","format":"video/h264-mp4","frame_rate":25},"muted":false}}},{"id":2,"type":"LoadImage","pos":[230,-50],"size":[315,314],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[5],"slot_index":0},{"name":"MASK","type":"MASK","links":null}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["image_fx_ (7).png","image"]},{"id":3,"type":"Echo_LoadModel","pos":[240,520],"size":[315,242],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"model","type":"MODEL_PIPE_E","links":[1],"slot_index":0},{"name":"face_detector","type":"MODEL_FACE_E","links":[2],"slot_index":1},{"name":"visualizer","type":"MODEL_VISUAL_E","links":[3],"slot_index":2}],"properties":{"Node name for S&R":"Echo_LoadModel"},"widgets_values":["stabilityai/sd-vae-ft-mse",true,"audio_drived",false,false,true,"V2"]},{"id":4,"type":"Echo_Sampler","pos":[650,140],"size":[315,494],"flags":{},"order":3,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":5},{"name":"audio","type":"AUDIO","link":4},{"name":"model","type":"MODEL_PIPE_E","link":1},{"name":"face_detector","type":"MODEL_FACE_E","link":2},{"name":"visualizer","type":"MODEL_VISUAL_E","link":3,"shape":7},{"name":"video_images","type":"IMAGE","link":null,"shape":7}],"outputs":[{"name":"image","type":"IMAGE","links":[6],"slot_index":0},{"name":"audio","type":"AUDIO","links":[7],"slot_index":1},{"name":"frame_rate","type":"FLOAT","links":[8],"slot_index":2}],"properties":{"Node name for S&R":"Echo_Sampler"},"widgets_values":["none",635373266,"randomize",2.5,30,25,16000,0.1,0.8,12,3,120,768,768,false]}],"links":[[1,3,0,4,2,"MODEL_PIPE_E"],[2,3,1,4,3,"MODEL_FACE_E"],[3,3,2,4,4,"MODEL_VISUAL_E"],[4,1,0,4,1,"AUDIO"],[5,2,0,4,0,"IMAGE"],[6,4,0,5,0,"IMAGE"],[7,4,1,5,1,"AUDIO"],[8,4,2,5,4,"FLOAT"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.8264462809917354,"offset":[314.8824427693278,170.65818602415717]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by smthemex** [comment]
Please choose an available custom npy file name. Currently, V2's custom pose only supports the methods I mentioned in readme.
The non original implementation code driven by pure video may be updated today
请选择可用的自定义npy文件名，目前V2的自定义pose仅支持我在readme提到的方法。纯视频驱动的非原版实现代码可能会今天更新

**Comment by Universalcow** [comment]
同样的问题，选择的none

**Comment by smthemex** [comment]
你查一下ComfyUI\custom_nodes\ComfyUI_EchoMimic\echomimic_v2\assets\halfbody_demo\pose\01 目录下是否有文件，这个地址是写死了的，除非你改了名字，不然不会找不到。要么是有些插件改了插件名，或者你不是git下载的，导致ComfyUI_EchoMimic目录名有类似ComfyUI_EchoMimic_main这样的问题

**Comment by smthemex** [comment]
的确是BUG 已修复
