### ISSUE TITLE
UnboundLocalError: local variable 'box_size' referenced before assignment

### ISSUE THREAD

**Issue by O-O1024** [smthemex/ComfyUI_EchoMimic#107]
运行 V2 版出现以下错误：

```
Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/ComfyUI/custom_nodes/ComfyUI_EchoMimic/EchoMimic_node.py", line 471, in em_main
    output_video=process_video_v2(image, audio_file, width, height, length, seed,
  File "/root/ComfyUI/custom_nodes/ComfyUI_EchoMimic/utils.py", line 93, in process_video_v2
    pose_img,_,_=visualizer(np.asarray(i),[5])
  File "/root/ComfyUI/custom_nodes/ComfyUI_EchoMimic/src/pose.py", line 124, in __call__
    pose_result_image, keypoints,box_size = self.estimate_pose(img, bboxes,filter_obj_done)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/ComfyUI/custom_nodes/ComfyUI_EchoMimic/src/pose.py", line 157, in estimate_pose
    return result_img, all_keypoints,box_size
UnboundLocalError: local variable 'box_size' referenced before assignment
```

查看输出，错误发生在对齐姿势：

![image](https://github.com/user-attachments/assets/6ce9bd47-4617-4e0a-88ea-d78bf353bfc7)

```
Starting the first frame gesture alignment based on the input image *** 基于输入图片，开始首帧手势缩放对齐 !
  0%|                                                                                                       | 0/60 [00:00<?, ?it/s]
0: 640x640 (no detections), 8.3ms
Speed: 2.7ms preprocess, 8.3ms inference, 0.6ms postprocess per image at shape (1, 3, 640, 640)

bboxes:  []
```

之前的姿势检查是正常的：

```
***** start infer video to npy files for drive pose ! ***** 

0: 640x640 1 person, 2 chairs, 1 potted plant, 7.4ms
Speed: 3.7ms preprocess, 7.4ms inference, 56.5ms postprocess per image at shape (1, 3, 640, 640)

bboxes:  [[146  30 624 765]] 


0: 640x640 1 person, 7.9ms
Speed: 2.6ms preprocess, 7.9ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 640)

bboxes:  [[109  36 654 767]]
```

**Comment by O-O1024** [comment]
😑 换了一个视频又可以了，似乎那个姿势模型会受噪声闪烁干扰

**Comment by smthemex** [comment]
YOLO首帧无法检测到人体，要么是你说的闪烁，要么是视频首帧是黑色的，我下次更新加个判断吧，
