### ISSUE TITLE
!!! Exception during processing !!! name 'AudioFileClip' is not defined，还是出现这个问题，请问怎么解决

### ISSUE THREAD

**Issue by zwdblend** [smthemex/ComfyUI_EchoMimic#108]
when use echo v2,need choice a pose dir,using default pose for testing !
!!! Exception during processing !!! name 'AudioFileClip' is not defined
Traceback (most recent call last):
  File "D:\ComfyUI-aki\ComfyUI-aki-v1.4\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki\ComfyUI-aki-v1.4\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki\ComfyUI-aki-v1.4\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki\ComfyUI-aki-v1.4\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI-aki\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 463, in em_main
    output_video=process_video_v2(image, audio_file, width, height, length, seed,
  File "D:\ComfyUI-aki\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic\utils.py", line 118, in process_video_v2
    audio_clip = AudioFileClip(uploaded_audio)
NameError: name 'AudioFileClip' is not defined

**Comment by smthemex** [comment]
pip install moviepy==2.1.1
