### ISSUE TITLE
Echo_Sampler的pose_dir找不到存放的npy文件

### ISSUE THREAD

**Issue by nothairyyq** [smthemex/ComfyUI_EchoMimic#119]
想尝试一下别的pose文件跑出来的效果，发现放在`/input/tensorrt_lite/1.npy`下comfyui并不能检索到。然而放在`input/tensorrt_lite/npy/1.npy`路径下pose_dir参数可以检索到npy这个文件夹，但是跑起来还是报错：Traceback (most recent call last):
  File "/workspace/lawks/stable-paw-comfyui/execution.py", line 330, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/lawks/stable-paw-comfyui/execution.py", line 205, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/lawks/stable-paw-comfyui/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/lawks/stable-paw-comfyui/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/lawks/stable-paw-comfyui/custom_nodes/ComfyUI_EchoMimic/EchoMimic_node.py", line 463, in em_main
    output_video=process_video_v2(image, audio_file, width, height, length, seed,
  File "/workspace/lawks/stable-paw-comfyui/custom_nodes/ComfyUI_EchoMimic/utils.py", line 177, in process_video_v2
    tgt_musk = center_resize_pad(tgt_musk, width, height) # 缩放裁剪遮罩，防止遮罩非正方形
  File "/workspace/lawks/stable-paw-comfyui/custom_nodes/ComfyUI_EchoMimic/utils.py", line 654, in center_resize_pad
    h, w = img.shape[:2]
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by smthemex** [comment]
我这个方法代码读取的是纯npy文件，不含其他的，官方的是需要索引的，所以其他方法保存到文件内容可能不同，包括我这个方法保持的都跟官方的有出入。
你要测试其他方法的npy，可能要提供一下该方法最后保存npy文件的代码，看一下是不是跟官方的一样。
你也可以把官方默认的npy文件夹改个名字，然后用你的文件替换，改个同名的，这样dir加载none时，就会跑你测试那个
检索问题，是要放在tensorrt_lite下，的任意非中文文件夹内，检索的是文件夹，而不是文件。
