### ISSUE TITLE
help me not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by henry19801109** [smthemex/ComfyUI_EchoMimic#122]
not enough values to unpack (expected 2, got 0),why,please help me.

**Comment by henry19801109** [comment]
got prompt
'🔥 - 7 Nodes not included in prompt but is activated'
****** refer in EchoMimic V2 mode!******
loaded temporal unet's pretrained weights from D:\AI\ComfyUI_windows_portable\ComfyUI\models\echo_mimic\unet ...
Load motion module params from D:\AI\ComfyUI_windows_portable\ComfyUI\models\echo_mimic\v2\motion_module.pth
Loaded 453.20928M-parameter motion module
use default pose pose_01 for running !
***** infer length is 50
!!! Exception during processing !!! not enough values to unpack (expected 2, got 0)
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 480, in em_main
    output_video=process_video_v2(image, audio_file, width, height, length, seed,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\utils.py", line 191, in process_video_v2
    tgt_musk = center_resize_pad(tgt_musk, width, height) # 缩放裁剪遮罩，防止遮罩非正方形
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\utils.py", line 668, in center_resize_pad
    h, w = img.shape[:2]
    ^^^^
ValueError: not enough values to unpack (expected 2, got 0)

Prompt executed in 23.42 seconds

**Comment by smthemex** [comment]
It's a bug ,update to fix it...

**Comment by henry19801109** [comment]
> It's a bug ,update to fix it...

what is part to update?,echo_miminc have been updated the latest，but still occur this error

**Comment by henry19801109** [comment]
> > It's a bug ,update to fix it...
> 
> what is part to update?,echo_miminc have been updated the latest，but still occur this error

The problem has been solved, thank you
