### ISSUE TITLE
Entry Not Found for url: https://huggingface.co/lambdalabs/sd-image-variations-diffusers/resolve/main/config.json.

### ISSUE THREAD

**Issue by whmc76** [smthemex/ComfyUI_EchoMimic#18]
!! Exception during processing!!! 404 Client Error. (Request ID: Root=1-66974cc3-2b82a2c81b3daee21fdbaf93;4e4a1fb8-761f-4da8-a239-b90bcd446c66)

Entry Not Found for url: https://huggingface.co/lambdalabs/sd-image-variations-diffusers/resolve/main/config.json.
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_slave\python_embeded\Lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "E:\IMAGE\ComfyUI_slave\python_embeded\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/lambdalabs/sd-image-variations-diffusers/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_slave\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_slave\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_slave\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_slave\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 396, in main_loader
    download_weights(weigths_current_path,"lambdalabs/sd-image-variations-diffusers",subfolder="unet",pt_name="config.json")
  File "E:\IMAGE\ComfyUI_slave\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 213, in download_weights
    pt_path = hf_hub_download(
              ^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_slave\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_slave\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1202, in hf_hub_download
    return _hf_hub_download_to_local_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_slave\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1420, in _hf_hub_download_to_local_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_slave\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_slave\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_slave\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_slave\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_slave\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 396, in _request_wrapper
    hf_raise_for_status(response)
  File "E:\IMAGE\ComfyUI_slave\python_embeded\Lib\site-packages\huggingface_hub\utils\_errors.py", line 315, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-66974cc3-2b82a2c81b3daee21fdbaf93;4e4a1fb8-761f-4da8-a239-b90bcd446c66)

Entry Not Found for url: https://huggingface.co/lambdalabs/sd-image-variations-diffusers/resolve/main/config.json.

**Comment by whmc76** [comment]
并且我已经在本地下载了模型 仍然会请求这个地址

**Comment by smthemex** [comment]
下载下来要改一下名字，前缀去掉。反复链接下载是因为插件在目录找不到config文件

**Comment by whmc76** [comment]
好的我试试

**Comment by daitaotao1** [comment]
@whmc76 @smthemex 下载后的VAE文件和confing放在哪个文件夹中？models/vae?

**Comment by ArvinC** [comment]
Entry Not Found for url: https://hf-mirror.com/lambdalabs/sd-image-variations-diffusers/resolve/main/diffusion_pytorch_model.bin.
我是这个问题，不知道在哪下载也不知道放在哪个目录下

**Comment by smthemex** [comment]
你们要看说明啊，里面已经把所有必须的文件名及文件位置列举好了，默认都会下载进去，如果你是自己在网页下载的，需要一一对应放进去，名字也要对应上，不能改名，不然插件怎么能识别到你的模型文件呢。

**Comment by ArvinC** [comment]
> 你们要看说明啊，里面已经把所有必须的文件名及文件位置列举好了，默认都会下载进去，如果你是自己在网页下载的，需要一一对应放进去，名字也要对应上，不能改名，不然插件怎么能识别到你的模型文件呢。

已经解决，模型文件只能在ComfyUI/model/echo_mimic中，而我的模型文件放在了其他地方用于共享模型加载，当前组件只会只会加载目录ComfyUI/model/echo_mimic

**Comment by nocynic** [comment]
Error occurred when executing Echo_LoadModel:

stabilityai/sd-vae-ft-mse does not appear to have a file named config.json.
