### ISSUE TITLE
Comfyui broken after installing custom node

### ISSUE THREAD

**Issue by SWAPv1** [smthemex/ComfyUI_EchoMimic#23]
Hello I need help, after restarting comfyui after installing the custom node, now comfyui will not load.

Anyway to revert?

Microsoft Windows [Version 10.0.19045.4651]
(c) Microsoft Corporation. All rights reserved.

B:\pinokio\api\comfyui.pinokio.git\ComfyUI>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && B:\pinokio\api\comfyui.pinokio.git\ComfyUI\env\Scripts\activate B:\pinokio\api\comfyui.pinokio.git\ComfyUI\env && python main.py 
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-07-18 
** Platform: Windows
** Python version: 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)]
** Python executable: B:\pinokio\api\comfyui.pinokio.git\ComfyUI\env\Scripts\python.exe
** ComfyUI Path: B:\pinokio\api\comfyui.pinokio.git\ComfyUI
** Log path: B:\pinokio\api\comfyui.pinokio.git\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: B:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: B:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds: B:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Marigold
   2.6 seconds: B:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "B:\pinokio\api\comfyui.pinokio.git\ComfyUI\main.py", line 80, in <module>
    import execution
  File "B:\pinokio\api\comfyui.pinokio.git\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "B:\pinokio\api\comfyui.pinokio.git\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "B:\pinokio\api\comfyui.pinokio.git\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "B:\pinokio\api\comfyui.pinokio.git\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "B:\pinokio\api\comfyui.pinokio.git\ComfyUI\comfy\model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "B:\pinokio\api\comfyui.pinokio.git\ComfyUI\comfy\model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "B:\pinokio\api\comfyui.pinokio.git\ComfyUI\env\lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
    _lazy_init()
  File "B:\pinokio\api\comfyui.pinokio.git\ComfyUI\env\lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init    
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

(env) (base) B:\pinokio\api\comfyui.pinokio.git\ComfyUI>

**Comment by smthemex** [comment]
try：
pip uninstall torchaudio torchvision torch xformers
pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121
pip install xformers==0.0.24
pip install facenet_pytorch

  facenet_pytorch  cause this issue

if you using cu118
pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu118

if you using conda
conda install pytorch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 pytorch-cuda=11.8 -c pytorch -c nvidia
or
conda install pytorch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 pytorch-cuda=12.1 -c pytorch -c nvidia
