### ISSUE TITLE
windows11安装后运行出错

### ISSUE THREAD

**Issue by pppyl** [smthemex/ComfyUI_EchoMimic#30]
got prompt
!!! Exception during processing!!! [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "C:\AI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 584, in em_main
    output_video = process_video(image, audio_file, width, height, length, seeds, facemask_ratio,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 175, in process_video
    video = pipe(
            ^^^^^
  File "C:\AI\ComfyUI\python\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\pipelines\pipeline_echo_mimic_pose.py", line 433, in __call__
    whisper_feature = self.audio_guider.audio2feat(audio_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\audio2feature.py", line 100, in audio2feat
    result = self.model.transcribe(audio_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\transcribe.py", line 85, in transcribe
    mel = log_mel_spectrogram(audio)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
            ^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\audio.py", line 44, in load_audio
    .run(cmd=["ffmpeg", "-nostdin"], capture_stdout=True, capture_stderr=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\python\Lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
              ^^^^^^^^^^
  File "C:\AI\ComfyUI\python\Lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\python\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\AI\ComfyUI\python\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by pppyl** [comment]
完全按照md安装的，各种都尝试了。模型也都全部手动下载了

**Comment by pppyl** [comment]
解决了，尝试运行了一下安装
pip install facenet_pytorch ffmpeg-python moviepy av
