### ISSUE TITLE
Broke comfyui install when installed via thee managers install via github link option

### ISSUE THREAD

**Issue by GamingDaveUk** [smthemex/ComfyUI_EchoMimic#4]
comfyui manager takes care of installing nodes and thier requirements well.
However for this it seems the node downloaded a none cuda Torch and replaced the one installed... never good. Comfyui now wont restart and I will need to re-install it (not, too much of a pain and update with dependencies may even work, but still an issue that needs fixing as most users use the manager). 

Error:
```
C:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-07-14 13:06:06.626661
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\AI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\AI\ComfyUI_windows_portable\ComfyUI
** Log path: C:\AI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   1.2 seconds: C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\main.py", line 80, in <module>
    import execution
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
    _lazy_init()
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by smthemex** [comment]
pip uninstall torchaudio torchvision torch xformers
pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121
pip install xformers==0.0.24

**Comment by GamingDaveUk** [comment]
> pip uninstall torchaudio torchvision torch xformers pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121 pip install xformers==0.0.24

running comfyui update with python dependencies got comfyui back up and running.
