### ISSUE TITLE
No such file or directory: 'ffmpeg'

### ISSUE THREAD

**Issue by thinkingjimmy** [smthemex/ComfyUI_EchoMimic#43]
I pip install:
```
    .pip_install(
        "ffmpeg-python",
        "dynamicprompts==0.30.2",
        "av",
        "facenet_pytorch",
        "moviepy",
        "IPython",
        "torchaudio==2.2.0",
    )
```
Error message:
```
!!! Exception during processing!!! [Errno 2] No such file or directory: 'ffmpeg'
Traceback (most recent call last):
  File "/comfyui/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/comfyui/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/comfyui/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/comfyui/custom_nodes/ComfyUI_EchoMimic/EchoMimic_node.py", line 678, in em_main
    output_video,audio_form_v= process_video(image, audio_file, width, height, length, seeds, facemask_ratio,
  File "/comfyui/custom_nodes/ComfyUI_EchoMimic/EchoMimic_node.py", line 208, in process_video
    video = pipe(
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/comfyui/custom_nodes/ComfyUI_EchoMimic/src/pipelines/pipeline_echo_mimic.py", line 394, in __call__
    whisper_feature = self.audio_guider.audio2feat(audio_path)
  File "/comfyui/custom_nodes/ComfyUI_EchoMimic/src/models/whisper/audio2feature.py", line 100, in audio2feat
    result = self.model.transcribe(audio_path)
  File "/comfyui/custom_nodes/ComfyUI_EchoMimic/src/models/whisper/whisper/transcribe.py", line 85, in transcribe
    mel = log_mel_spectrogram(audio)
  File "/comfyui/custom_nodes/ComfyUI_EchoMimic/src/models/whisper/whisper/audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
  File "/comfyui/custom_nodes/ComfyUI_EchoMimic/src/models/whisper/whisper/audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
  File "/usr/local/lib/python3.10/site-packages/ffmpeg/_run.py", line 313, in run
    process = run_async(
  File "/usr/local/lib/python3.10/site-packages/ffmpeg/_run.py", line 284, in run_async
    return subprocess.Popen(
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

**Comment by thinkingjimmy** [comment]
fixed: 

.apt_install("ffmpeg")
