### ISSUE TITLE
RuntimeError: Unsupported file type: FLAC

### ISSUE THREAD

**Issue by Miao-WangHao** [smthemex/ComfyUI_EchoMimic#46]
Traceback (most recent call last):
  File "/home/wanghao/work/数字人/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/wanghao/work/数字人/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/wanghao/work/数字人/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/wanghao/work/数字人/ComfyUI/custom_nodes/ComfyUI_EchoMimic/EchoMimic_node.py", line 675, in em_main
    torchaudio.save(buff, audio["waveform"].squeeze(0), audio["sample_rate"], format="FLAC")
  File "/home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torchaudio/backend/sox_io_backend.py", line 417, in save
    torchaudio.lib._torchaudio_sox.save_audio_fileobj(
RuntimeError: Unsupported file type: FLAC
这个问题是啥阿？怎么解决呢？

**Comment by smthemex** [comment]
可能你的ffmpeg的版本不同，没有flac的，不过不应该啊，应该都有的

**Comment by Miao-WangHao** [comment]
> 可能你的ffmpeg的版本不同，没有flac的，不过不应该啊，应该都有的

非常恐怖，我单独跑Echomimic没问题，在comfyui里跑就有这个问题。

**Comment by smthemex** [comment]
这是comfyUI标准的音频保存代码，你试试标准的音频保存节点能不能跑通

**Comment by Miao-WangHao** [comment]
> 这是comfyUI标准的音频保存代码，你试试标准的音频保存节点能不能跑通

阿这....ffmpeg==1.4的。我对这个UI操作还不熟，怎么添加标准的音频保存阿，这样吗
![Uploading 11111.jpg…]()

**Comment by smthemex** [comment]
comfyUI自带了audio保存节点，你加载一个，然后用自带的连接上，看能不能保存

**Comment by Miao-WangHao** [comment]
> comfyUI自带了audio保存节点，你加载一个，然后用自带的连接上，看能不能保存

哦明白了，只放置这两个节点连起来，跑一下。我刚才做了，直接报错，还是这个问题：
FETCH DATA from: /home/wanghao/work/数字人/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
got prompt
/home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torchaudio/backend/sox_io_backend.py:416: UserWarning: File-like object support in sox_io backend is deprecated, and will be removed in v2.1. See https://github.com/pytorch/audio/issues/2950 for the detail.Please migrate to the new dispatcher, or use soundfile backend.
  warnings.warn(_deprecation_message)

!!! Exception during processing!!! Unsupported file type: FLAC
Exception raised from get_precision at /__w/audio/audio/pytorch/audio/torchaudio/csrc/sox/utils.cpp:421 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x77bdc039e4d7 in /home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x77bdc036836b in /home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: torchaudio::sox_utils::get_signalinfo(at::Tensor const*, long, std::string, bool) + 0x302 (0x77bc4b451bc2 in /home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio_sox.so)
frame #3: <unknown function> + 0x3ca46 (0x77bc4b03ca46 in /home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torchaudio/lib/_torchaudio_sox.so)
frame #4: <unknown function> + 0x3953e (0x77bc4b03953e in /home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torchaudio/lib/_torchaudio_sox.so)
frame #5: <unknown function> + 0x35d07 (0x77bc4b035d07 in /home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torchaudio/lib/_torchaudio_sox.so)
frame #6: python() [0x4fc887]
<omitting python frames>
frame #11: python() [0x5080ee]
frame #28: python() [0x508377]
frame #29: python() [0x5e3155]
frame #30: python() [0x5e30b4]
frame #31: <unknown function> + 0x94ac3 (0x77bdc5494ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #32: <unknown function> + 0x126850 (0x77bdc5526850 in /lib/x86_64-linux-gnu/libc.so.6)

Traceback (most recent call last):
  File "/home/wanghao/work/数字人/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/wanghao/work/数字人/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/wanghao/work/数字人/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/wanghao/work/数字人/ComfyUI/comfy_extras/nodes_audio.py", line 156, in save_audio
    torchaudio.save(buff, waveform, audio["sample_rate"], format="FLAC")
  File "/home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torchaudio/backend/sox_io_backend.py", line 417, in save
    torchaudio.lib._torchaudio_sox.save_audio_fileobj(
RuntimeError: Unsupported file type: FLAC
Exception raised from get_precision at /__w/audio/audio/pytorch/audio/torchaudio/csrc/sox/utils.cpp:421 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x77bdc039e4d7 in /home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x77bdc036836b in /home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: torchaudio::sox_utils::get_signalinfo(at::Tensor const*, long, std::string, bool) + 0x302 (0x77bc4b451bc2 in /home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio_sox.so)
frame #3: <unknown function> + 0x3ca46 (0x77bc4b03ca46 in /home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torchaudio/lib/_torchaudio_sox.so)
frame #4: <unknown function> + 0x3953e (0x77bc4b03953e in /home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torchaudio/lib/_torchaudio_sox.so)
frame #5: <unknown function> + 0x35d07 (0x77bc4b035d07 in /home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/torchaudio/lib/_torchaudio_sox.so)
frame #6: python() [0x4fc887]
<omitting python frames>
frame #11: python() [0x5080ee]
frame #28: python() [0x508377]
frame #29: python() [0x5e3155]
frame #30: python() [0x5e30b4]
frame #31: <unknown function> + 0x94ac3 (0x77bdc5494ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #32: <unknown function> + 0x126850 (0x77bdc5526850 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by smthemex** [comment]
你把那行代码里的 format="FLAC" 去掉试试，或者升级ffmgpeg 我没有测试Linux的系统。

**Comment by Miao-WangHao** [comment]
> 你把那行代码里的 format="FLAC" 去掉试试，或者升级ffmgpeg 我没有测试Linux的系统。

我去了，报错说缺少参数format。然后我把FLAC小写，报了新错误：
Traceback (most recent call last):
  File "/home/wanghao/work/数字人/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/wanghao/work/数字人/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/wanghao/work/数字人/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/wanghao/work/数字人/ComfyUI/custom_nodes/ComfyUI_EchoMimic/EchoMimic_node.py", line 699, in em_main
    output_video, audio_form_v = process_video(image, audio_file, width, height, length, seeds, facemask_ratio,
  File "/home/wanghao/work/数字人/ComfyUI/custom_nodes/ComfyUI_EchoMimic/EchoMimic_node.py", line 132, in process_video
    det_bboxes, probs = face_detector.detect(face_img)
  File "/home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/facenet_pytorch/models/mtcnn.py", line 346, in detect
    batch_boxes, batch_points = detect_face(
  File "/home/wanghao/anaconda3/envs/test/lib/python3.10/site-packages/facenet_pytorch/models/utils/detect_face.py", line 63, in detect_face
    boxes, image_inds = boxes[pick], image_inds[pick]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by smthemex** [comment]
新的错误不是声音了，你用的什么硬件?

**Comment by Miao-WangHao** [comment]
> 新的错误不是声音了，你用的什么硬件?
3060显卡，挺奇怪的，我也没动其他的代码。我刚跑过LivePortrait，是正常的。

**Comment by cskkx1** [comment]
同样的问题
