### ISSUE TITLE
ComfyUI_EchoMimic 模块导入时出现 IndexError

### ISSUE THREAD

**Issue by unsiao** [smthemex/ComfyUI_EchoMimic#73]
### 问题描述

在尝试运行 `ComfyUI` 的 `main.py` 文件（`(comfyui) C:\Users\zz\ComfyUI>python main.py`）时，遇到了 `ComfyUI_EchoMimic` 模块导入错误。尽管程序仍尝试启动服务器（可通过 `http://127.0.0.1:8188` 访问 GUI），但这个错误可能会影响相关功能的正常使用。

#### 详细报错信息

```
Traceback (most recent call last):
  File "C:\Users\zz\ComfyUI\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\__init__.py", line 2, in <module>
    from.EchoMimic_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 23, in <module>
    from.hallo.video_sr import run_realesrgan,pre_u_loader
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\hallo\video_sr.py", line 18, in <module>
    from.basicsr.utils import imwrite, img2tensor, tensor2img
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\hallo\basicsr\__init__.py", line 3, in <module>
    from.hallo_archs import *
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\hallo\basicsr\hallo_archs\__init__.py", line 5, in <module>
    from..utils import get_root_logger, scandir
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\hallo\basicsr\utils\__init__.py", line 4, in <module>
    from.misc import check_resume, get_time_str, make_exp_dirs, mkdir_and_rename, scandir, set_random_seed, sizeof_fmt
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\hallo\basicsr\utils\misc.py", line 12, in <module>
    IS_HIGH_VERSION = [int(m) for m in list(re.findall(r"^([0-9]+)\.([0-9]+)\.([0-9]+)([^0-9][a-zA-Z0-9]*)?(\+git.*)?$",\
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
Cannot import C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic module for custom nodes: list index out of range
Import times for custom nodes:
   0.0 seconds: C:\Users\zz\ComfyUI\custom_nodes\websocket_image_save.py
   6.0 seconds (IMPORT FAILED): C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic
```

#### 环境信息

- **操作系统**：[你的操作系统版本，例如 Windows 10/11 等]
- **显卡信息**：NVIDIA GeForce RTX 3070 Laptop GPU，总显存 8192 MB（`Total VRAM 8192 MB`），内存 65389 MB（`total RAM 65389 MB`）
- **PyTorch 版本**：2.6.0.dev20241118+cu124
- **ComfyUI 相关版本信息（如果有）**：[请提供 ComfyUI 的版本，如果知道的话]
- **ComfyUI_EchoMimic 版本信息（如果有）**：[请提供插件版本，如果知道的话]

#### 已尝试的解决方法

- 已检查并确认相关依赖库（如之前报错中提到的相关库）是否安装，但问题依旧存在。
- 尝试重新安装 ComfyUI 和 ComfyUI_EchoMimic 插件，但没有解决问题。

希望开发团队能帮忙查看和解决这个问题，感谢！

```完整日志
(comfyui) C:\Users\zz\ComfyUI>pip install omegaconf
Collecting omegaconf
  Using cached omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf)
  Using cached antlr4_python3_runtime-4.9.3-py3-none-any.whl
Requirement already satisfied: PyYAML>=5.1.0 in c:\users\zz\anaconda3\envs\comfyui\lib\site-packages (from omegaconf) (6.0.2)
Using cached omegaconf-2.3.0-py3-none-any.whl (79 kB)
Installing collected packages: antlr4-python3-runtime, omegaconf
Successfully installed antlr4-python3-runtime-4.9.3 omegaconf-2.3.0

(comfyui) C:\Users\zz\ComfyUI>python main.py
Total VRAM 8192 MB, total RAM 65389 MB
pytorch version: 2.6.0.dev20241118+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Users\zz\ComfyUI\web
Traceback (most recent call last):
  File "C:\Users\zz\ComfyUI\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\__init__.py", line 2, in <module>
    from .EchoMimic_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 21, in <module>
    from .src.utils.motion_utils import motion_sync
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\utils\motion_utils.py", line 1, in <module>
    from skimage.transform import estimate_transform, AffineTransform
ModuleNotFoundError: No module named 'skimage'

Cannot import C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic module for custom nodes: No module named 'skimage'

Import times for custom nodes:
   0.0 seconds: C:\Users\zz\ComfyUI\custom_nodes\websocket_image_save.py
   6.2 seconds (IMPORT FAILED): C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic

Starting server

To see the GUI go to: http://127.0.0.1:8188

Stopped server

(comfyui) C:\Users\zz\ComfyUI>pip install scikit-image
Collecting scikit-image
  Using cached scikit_image-0.24.0-cp312-cp312-win_amd64.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\zz\anaconda3\envs\comfyui\lib\site-packages (from scikit-image) (1.26.4)
Requirement already satisfied: scipy>=1.9 in c:\users\zz\anaconda3\envs\comfyui\lib\site-packages (from scikit-image) (1.14.1)
Requirement already satisfied: networkx>=2.8 in c:\users\zz\anaconda3\envs\comfyui\lib\site-packages (from scikit-image) (3.4.2)
Requirement already satisfied: pillow>=9.1 in c:\users\zz\anaconda3\envs\comfyui\lib\site-packages (from scikit-image) (11.0.0)
Requirement already satisfied: imageio>=2.33 in c:\users\zz\anaconda3\envs\comfyui\lib\site-packages (from scikit-image) (2.36.0)
Collecting tifffile>=2022.8.12 (from scikit-image)
  Using cached tifffile-2024.9.20-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: packaging>=21 in c:\users\zz\anaconda3\envs\comfyui\lib\site-packages (from scikit-image) (24.2)
Collecting lazy-loader>=0.4 (from scikit-image)
  Using cached lazy_loader-0.4-py3-none-any.whl.metadata (7.6 kB)
Using cached scikit_image-0.24.0-cp312-cp312-win_amd64.whl (12.9 MB)
Using cached lazy_loader-0.4-py3-none-any.whl (12 kB)
Using cached tifffile-2024.9.20-py3-none-any.whl (228 kB)
Installing collected packages: tifffile, lazy-loader, scikit-image
Successfully installed lazy-loader-0.4 scikit-image-0.24.0 tifffile-2024.9.20

(comfyui) C:\Users\zz\ComfyUI>python main.py
Total VRAM 8192 MB, total RAM 65389 MB
pytorch version: 2.6.0.dev20241118+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Users\zz\ComfyUI\web
Traceback (most recent call last):
  File "C:\Users\zz\ComfyUI\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\__init__.py", line 2, in <module>
    from .EchoMimic_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 23, in <module>
    from .hallo.video_sr import run_realesrgan,pre_u_loader
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\hallo\video_sr.py", line 18, in <module>
    from .basicsr.utils import imwrite, img2tensor, tensor2img
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\hallo\basicsr\__init__.py", line 3, in <module>
    from .hallo_archs import *
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\hallo\basicsr\hallo_archs\__init__.py", line 5, in <module>
    from ..utils import get_root_logger, scandir
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\hallo\basicsr\utils\__init__.py", line 4, in <module>
    from .misc import check_resume, get_time_str, make_exp_dirs, mkdir_and_rename, scandir, set_random_seed, sizeof_fmt
  File "C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic\hallo\basicsr\utils\misc.py", line 12, in <module>
    IS_HIGH_VERSION = [int(m) for m in list(re.findall(r"^([0-9]+)\.([0-9]+)\.([0-9]+)([^0-9][a-zA-Z0-9]*)?(\+git.*)?$",\
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

Cannot import C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic module for custom nodes: list index out of range

Import times for custom nodes:
   0.0 seconds: C:\Users\zz\ComfyUI\custom_nodes\websocket_image_save.py
   6.0 seconds (IMPORT FAILED): C:\Users\zz\ComfyUI\custom_nodes\ComfyUI_EchoMimic

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by luz941216** [comment]
Echo_Sampler
tuple index out of range
这个报错是什么原因呢
