### ISSUE TITLE
RuntimeWarning: invalid value encountered in cast

### ISSUE THREAD

**Issue by ysxk** [smthemex/ComfyUI_EchoMimic#78]
系统：windows server 2022
显卡：a100
环境：秋叶包
模型已全部下载comfyui\models\echomimic\下的vae和sd-vae-ft-mse中都存放了模型，也试过把工作流vae的键值改为vae或者sd-vae-ft-mse
均会出现视频黑屏的情况
开关降噪都会黑屏
以下是完整日志
我注意到其中有一个远程主机断开连接，但我不知道是不是在下载vae？
![image](https://github.com/user-attachments/assets/a60df12e-9dfd-4546-8391-5d1fd15afc74)
rompt executed in 19.68 seconds
got prompt
****** refer in EchoMimic V1 mode!******
loaded temporal unet's pretrained weights from E:\ComfyUI-aki-v1.4\models\echo_mimic\unet ...
Loaded 0.0M-parameter motion module
**** Use  audio drive video! ****
video in 5 FPS, audio idx in 50FPS
whisper_chunks: (298, 50, 384)
audio_fea_final: torch.Size([1, 298, 50, 384])
ref_image_latents shape: torch.Size([1, 4, 16, 64])
face_mask_tensor shape: torch.Size([1, 1, 1, 128, 512])
face_locator_tensor shape: torch.Size([2, 320, 1, 16, 64])
**** final_length is : 1 ****
Moviepy - Building video E:\ComfyUI-aki-v1.4\output\409309_audio.mp4.
MoviePy - Writing audio in 409309_audioTEMP_MPY_wvf_snd.mp4
MoviePy - Done.
Moviepy - Writing video E:\ComfyUI-aki-v1.4\output\409309_audio.mp4

Moviepy - Done !
Moviepy - video ready E:\ComfyUI-aki-v1.4\output\409309_audio.mp4
**** savingE:\ComfyUI-aki-v1.4\output\409309_echo.mp4 at E:\ComfyUI-aki-v1.4\output\409309_audio.mp4 ****
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Prompt executed in 47.42 seconds
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.4\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\ComfyUI-aki-v1.4\python\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
got prompt
****** refer in EchoMimic V2 mode!******
loaded temporal unet's pretrained weights from E:\ComfyUI-aki-v1.4\models\echo_mimic\unet ...
Load motion module params from E:\ComfyUI-aki-v1.4\models\echo_mimic\v2\motion_module.pth
Loaded 453.20928M-parameter motion module
when use echo v2,need choice a pose dir,for get error using default pose !
***** infer length is 296
poses_tensor:torch.Size([1, 3, 296, 512, 512])
video in 5 FPS, audio idx in 50FPS
ori: tensor(-3.9043, device='cuda:0', dtype=torch.float16) tensor(3.9043, device='cuda:0', dtype=torch.float16)
latents shape:torch.Size([1, 4, 296, 64, 64]), video_length:296
**** final_length is : 296 ****
Moviepy - Building video E:\ComfyUI-aki-v1.4\output\413088_audio.mp4.
MoviePy - Writing audio in 413088_audioTEMP_MPY_wvf_snd.mp4
MoviePy - Done.
Moviepy - Writing video E:\ComfyUI-aki-v1.4\output\413088_audio.mp4

Moviepy - Done !
Moviepy - video ready E:\ComfyUI-aki-v1.4\output\413088_audio.mp4
**** savingE:\ComfyUI-aki-v1.4\output\413088_echo.mp4 at E:\ComfyUI-aki-v1.4\output\413088_audio.mp4 ****
Prompt executed in 61.82 seconds

**Comment by ysxk** [comment]
能不能通过修改代码来指定模型路径？

**Comment by smthemex** [comment]
你的图片有问题，不是VAE的问题，ref_image_latents shape: torch.Size([1, 4, 16, 64]) 这里可以看得出来，你的输入图片的格式不对，你换个一个别的图片，试试

**Comment by ysxk** [comment]
又试了一次，使用的是E:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic\echomimic_v2\EMTD_dataset\ref_imgs_by_FLUX\woman
也就是仓库中自带的图片，依然是纯黑的视频
***** infer length is 336
poses_tensor:torch.Size([1, 3, 336, 512, 512])
video in 24 FPS, audio idx in 50FPS
ori: tensor(-3.9043, device='cuda:0', dtype=torch.float16) tensor(3.9043, device='cuda:0', dtype=torch.float16)
latents shape:torch.Size([1, 4, 336, 64, 64]), video_length:336
**** final_length is : 336 ****
E:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic\src\utils\util.py:98: RuntimeWarning: invalid value encountered in cast
  x = (x * 255).numpy().astype(np.uint8)

Prompt executed in 30.76 seconds
got prompt
when use echo v2,need choice a pose dir,for get error using default pose !
***** infer length is 336
poses_tensor:torch.Size([1, 3, 336, 512, 512])
video in 24 FPS, audio idx in 50FPS
ori: tensor(-3.9043, device='cuda:0', dtype=torch.float16) tensor(3.9043, device='cuda:0', dtype=torch.float16)
latents shape:torch.Size([1, 4, 336, 64, 64]), video_length:336
**** final_length is : 336 ****
E:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic\src\utils\util.py:98: RuntimeWarning: invalid value encountered in cast
  x = (x * 255).numpy().astype(np.uint8)

**Comment by smthemex** [comment]
numpy版本不对？ 你pip show numpy  看看版本是多少 官方要求是1.26.4

**Comment by ysxk** [comment]
numpy版本是对的，我刚刚看到这个有关numpy的报错特地看了一下v2的依赖文件，v2要求的是1.23.5，我装了1.23.5也是黑屏，我再装回1.26.4试试

**Comment by ysxk** [comment]
重装过1.26.4后是一样的情况
![f0b1dac9ed2188fc8863962e656a71d](https://github.com/user-attachments/assets/b92afa79-4aa1-49af-bec6-4fb87043942d)

**Comment by ysxk** [comment]
装完之后有重启过comfyui的

**Comment by smthemex** [comment]
还是np相关依赖的问题，你这个最后的报错看着眼熟

**Comment by smthemex** [comment]
或者你下一个fp16的模型，然后去掉名字去掉_fp16

**Comment by ysxk** [comment]
fp16的echomimic2吗
还是vae？

**Comment by ysxk** [comment]
我找了下，echomimic 和vae都没在huggingface上找到标了fp16的版本

**Comment by ysxk** [comment]
又折腾了几个小时，用ubuntu server自己动手安装了comfyui和echomimicv2
还是一样的报错
**** final_length is : 118 ****
/root/comfyui/custom_nodes/ComfyUI_EchoMimic/src/utils/util.py:98: RuntimeWarning: invalid value encountered in cast
  x = (x * 255).numpy().astype(np.uint8)
是我运气太差了么2333
新机器上也是一样的numpy1.26.4
我还怀疑过镜像源，但是换了好几个镜像源安装np都是如此

**Comment by ysxk** [comment]
....我想可能是我的工作流有问题，我在https://github.com/smthemex/ComfyUI_EchoMimic/issues/45看到一位朋友的工作流，我完全照抄了过来，现在已经能够正常出视频了

**Comment by ysxk** [comment]
暂时不清楚问题出在哪个参数，我打算明天睡醒再试试，到时候给您反馈，以便能帮助到更多人

**Comment by smthemex** [comment]
SDXL vae是老毛病了，所以官方要用ft的版本，主要是fp16的问题，可能是你的A100的缘故，按理，你从菜单直接模型加载和sampler节点，应该是能跑的。但是加入了其他节点，就不好说了
