### ISSUE TITLE
Echo_LoadModel exceptions must derive from BaseException

### ISSUE THREAD

**Issue by Pancat009** [smthemex/ComfyUI_EchoMimic#86]
装好了节点，尝试使用v2
![image](https://github.com/user-attachments/assets/48a96087-6d0a-407a-8753-345a9407bbff)
但是因为服务器没有办法联外网，不知道是不是缺了什么文件，已经手动安装了
Already installed the node, since the server can't directly connect to huggingface, not sure if I'm missing other things.

/models/echo_mimic/vae
--diffusion_pytorch_model.safetensors

/models/echo_mimic/v2
--denoising_unet.pth
--motion_module.pth
--pose_encoder.pth
--reference_unet.pth

**Comment by Pancat009** [comment]
现在路径里有文件：

/models/echo_mimic/audio_processor
whisper_tiny.pt

/models/echo_mimic/unet
--config.json
--diffusion_pytorch_model.safetensors

/models/echo_mimic/vae
--config.json
--diffusion_pytorch_model.safetensors

/models/echo_mimic/v2
--denoising_unet.pth
--motion_module.pth
--pose_encoder.pth
--reference_unet.pth

但是还是报一样的错，
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\python\lib\site-packages\huggingface_hub\file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\python\lib\site-packages\huggingface_hub\file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\python\lib\site-packages\huggingface_hub\file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\python\lib\site-packages\huggingface_hub\file_download.py", line 395, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\python\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\python\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\python\lib\site-packages\huggingface_hub\utils\_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\python\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /BadToBest/EchoMimic/resolve/main/reference_unet.pth (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001ED947C8FD0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: addfb3f7-e9b9-4b58-a805-6630baa89533)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 183, in main_loader
    re_ckpt = download_weights(weigths_current_path, "BadToBest/EchoMimic", pt_name="reference_unet.pth")
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\custom_nodes\ComfyUI_EchoMimic\utils.py", line 361, in download_weights
    pt_path = hf_hub_download(
  File "<enhanced_experience patches.hfmirror.huggingface_hub>", line 47, in hf_hub_download_wrapper_inner
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\python\lib\site-packages\huggingface_hub\file_download.py", line 1202, in hf_hub_download
    return _hf_hub_download_to_local_dir(
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\python\lib\site-packages\huggingface_hub\file_download.py", line 1440, in _hf_hub_download_to_local_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "D:\StableDIffusion\comfyui-aki-py311-torch240-cuda124\python\lib\site-packages\huggingface_hub\file_download.py", line 1826, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

有办法可以直接下载吗？或者有必需文件结构的参考吗？

**Comment by smthemex** [comment]
VAE地址填写本地路径，不要填写repo

**Comment by Pancat009** [comment]
> VAE地址填写本地路径，不要填写repo

填写本地路径：D:/<SD>/models/echo_mimic/vae
报错：An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

好像还是不能绕过。。。

**Comment by smthemex** [comment]
你的路径都不对，默认会寻找comfyUI/models/echo_mimic/vae 你把它提取出去干什么

**Comment by youlingxxy** [comment]
<img width="511" alt="Snipaste_2024-11-26_14-22-02" src="https://github.com/user-attachments/assets/3f9b89f1-2d7b-44f7-ae36-5b4a262ee9cf">
<img width="1046" alt="Snipaste_2024-11-26_14-22-48" src="https://github.com/user-attachments/assets/6dee21f4-1c2c-4b23-a439-ed28f52c7946">
这是我的路径，还是有一样的报错

**Comment by youlingxxy** [comment]
> <img alt="Snipaste_2024-11-26_14-22-02" width="511" src="https://private-user-images.githubusercontent.com/50067324/389819481-3f9b89f1-2d7b-44f7-ae36-5b4a262ee9cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDMzMTEsIm5iZiI6MTczMjYwMzAxMSwicGF0aCI6Ii81MDA2NzMyNC8zODk4MTk0ODEtM2Y5Yjg5ZjEtMmQ3Yi00NGY3LWFlMzYtNWI0YTI2MmVlOWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA2MzY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MGViZTVlNTMwMDg0ZjhmY2JiNjMzYTc3NTViYzVlYjRkMmM3YjcyYTVhOGVjZmZiNDBhOTQzYmYwNzY2OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4gMo-1W1EP2bnkpEuj-yV8QftpsDYeZYGoDTMWfTaU4"> <img alt="Snipaste_2024-11-26_14-22-48" width="1046" src="https://private-user-images.githubusercontent.com/50067324/389819602-6dee21f4-1c2c-4b23-a439-ed28f52c7946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDMzMTEsIm5iZiI6MTczMjYwMzAxMSwicGF0aCI6Ii81MDA2NzMyNC8zODk4MTk2MDItNmRlZTIxZjQtMWMyYy00YjIzLWE0MzktZWQyOGY1MmM3OTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA2MzY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZjcyZGM4N2YzZDFjYjk0MjdlMTdmNzExYjFiMzkxNDk4OGI2YTE4OGU4N2VlNGFkNTE3MzJlMDYyOWMwNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.deDfvalOwhuzDNfz46DBCqStnj9bmLpDwL4MmKstfgY"> 这是我的路径，还是有一样的报错

这个节点过了，解决方案：下载模型文件时候前面默认带了前缀，要删掉就可以找到文件了

**Comment by Pancat009** [comment]
> > <img alt="Snipaste_2024-11-26_14-22-02" width="511" src="https://private-user-images.githubusercontent.com/50067324/389819481-3f9b89f1-2d7b-44f7-ae36-5b4a262ee9cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDMzMTEsIm5iZiI6MTczMjYwMzAxMSwicGF0aCI6Ii81MDA2NzMyNC8zODk4MTk0ODEtM2Y5Yjg5ZjEtMmQ3Yi00NGY3LWFlMzYtNWI0YTI2MmVlOWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA2MzY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MGViZTVlNTMwMDg0ZjhmY2JiNjMzYTc3NTViYzVlYjRkMmM3YjcyYTVhOGVjZmZiNDBhOTQzYmYwNzY2OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4gMo-1W1EP2bnkpEuj-yV8QftpsDYeZYGoDTMWfTaU4"> <img alt="Snipaste_2024-11-26_14-22-48" width="1046" src="https://private-user-images.githubusercontent.com/50067324/389819602-6dee21f4-1c2c-4b23-a439-ed28f52c7946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDMzMTEsIm5iZiI6MTczMjYwMzAxMSwicGF0aCI6Ii81MDA2NzMyNC8zODk4MTk2MDItNmRlZTIxZjQtMWMyYy00YjIzLWE0MzktZWQyOGY1MmM3OTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA2MzY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZjcyZGM4N2YzZDFjYjk0MjdlMTdmNzExYjFiMzkxNDk4OGI2YTE4OGU4N2VlNGFkNTE3MzJlMDYyOWMwNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.deDfvalOwhuzDNfz46DBCqStnj9bmLpDwL4MmKstfgY"> 这是我的路径，还是有一样的报错
> 
> 这个节点过了，解决方案：下载模型文件时候前面默认带了前缀，要删掉，就可以找到文件了

想问一下具体路径是怎么样的？
我试了 完整路径、/models/echo_mimic/vae、/echo_mimic/vae、/vae 都不行？

**Comment by Pancat009** [comment]
再添加 image_encoder 似乎可以，
添加完整之后，原来的 stabilityai/sd-vae-ft-mse 也不影响，

但随之而来的我的第二个节点也报错
Prompt executed in 22.45 seconds
got prompt
****** refer in EchoMimic V2 mode!******
loaded temporal unet's pretrained weights from C:\comfyui-aki-torch240\models\echo_mimic\unet ...
Load motion module params from C:\comfyui-aki-torch240\models\echo_mimic\v2\motion_module.pth
Loaded 453.20928M-parameter motion module
when use echo v2,need choice a pose dir,for get error using default pose !
***** infer length is 120
poses_tensor:torch.Size([1, 3, 120, 512, 512])
!!! Exception during processing !!! [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "C:\comfyui-aki-torch240\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\comfyui-aki-torch240\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\comfyui-aki-torch240\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\comfyui-aki-torch240\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 448, in em_main
    output_video=process_video_v2(image, audio_file, width, height, length, seed,
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\utils.py", line 85, in process_video_v2
    video = pipe(
  File "C:\comfyui-aki-torch240\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\echomimic_v2\src\pipelines\pipeline_echomimicv2.py", line 466, in __call__
    whisper_feature = self.audio_guider.audio2feat(audio_path)
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\audio2feature.py", line 100, in audio2feat
    result = self.model.transcribe(audio_path)
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\transcribe.py", line 85, in transcribe
    mel = log_mel_spectrogram(audio)
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\comfyui-aki-torch240\python\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\comfyui-aki-torch240\python\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1720, in runner
  File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 224, in sentry_patched_popen_init
  File "C:\comfyui-aki-torch240\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\comfyui-aki-torch240\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by smthemex** [comment]
秋叶包的ffmpeg按[ffmpeg](https://github.com/smthemex/ComfyUI_EchoMimic/issues/53) 的方法解决，你们提问之前麻烦看一下issues的解决路子，我有强迫症，看到红点就要打开，很讨厌啊！！！！！！

**Comment by xiusidunhuren** [comment]
请问解决了吗 我也是这个报错
