### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by Pancat009** [smthemex/ComfyUI_EchoMimic#92]
Prompt executed in 11.65 seconds
got prompt
****** refer in EchoMimic V2 mode!******
loaded temporal unet's pretrained weights from C:\comfyui-aki-torch240\models\echo_mimic\unet ...
Load motion module params from C:\comfyui-aki-torch240\models\echo_mimic\v2\motion_module.pth
Loaded 453.20928M-parameter motion module
when use echo v2,need choice a pose dir,for get error using default pose !
***** infer length is 120
poses_tensor:torch.Size([1, 3, 120, 512, 512])
!!! Exception during processing !!! [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "C:\comfyui-aki-torch240\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\comfyui-aki-torch240\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\comfyui-aki-torch240\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\comfyui-aki-torch240\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 448, in em_main
    output_video=process_video_v2(image, audio_file, width, height, length, seed,
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\utils.py", line 85, in process_video_v2
    video = pipe(
  File "C:\comfyui-aki-torch240\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\echomimic_v2\src\pipelines\pipeline_echomimicv2.py", line 466, in __call__
    whisper_feature = self.audio_guider.audio2feat(audio_path)
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\audio2feature.py", line 100, in audio2feat
    result = self.model.transcribe(audio_path)
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\transcribe.py", line 85, in transcribe
    mel = log_mel_spectrogram(audio)
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
  File "C:\comfyui-aki-torch240\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\comfyui-aki-torch240\python\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\comfyui-aki-torch240\python\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1720, in runner
  File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 224, in sentry_patched_popen_init
  File "C:\comfyui-aki-torch240\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\comfyui-aki-torch240\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

奇怪的是我两台机器都是cuda12.6, 
ffmpeg-python==0.2.0
torch==2.4.0+cu124
torchaudio==2.4.0+cu124
torchmetrics==1.4.0
但是一台可以，另一台不行

**Comment by smthemex** [comment]
这就是秋叶包这种半封装带来的弊病， [WinError 2] 系统找不到指定的文件就是ffmpeg在沙箱倒腾了一下，没有找到路径。你自己手动添加吧，这个破问题，占了issues的一大半，而且都是秋叶包

**Comment by GoToBoy** [comment]
大佬上个二维码吧
