### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusers'

### ISSUE THREAD

**Issue by liubai021** [smthemex/ComfyUI_EchoMimic#93]
我这里一直提示我缺少diffusers模块
我按照GPT给出的方法在根目录跟插件目录都pin了，但还是一直这样
请问有遇到相同问题的用什么方法解决吗。

Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\__init__.py", line 2, in <module>
    from .EchoMimic_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 11, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler
ModuleNotFoundError: No module named 'diffusers'

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic module for custom nodes: No module named 'diffusers'
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
![微信截图_20241127141705](https://github.com/user-attachments/assets/b5774295-917f-45c6-bf0b-6ec085ea6944)

**Comment by xuhuang37** [comment]
same issue

**Comment by smthemex** [comment]
diffusers 是comfyUI便携包的标配，不可能缺少的，唯一的可能是你的diffusers版本太低，或者你的便携包不是官方版本的。这不是插件的问题，是你的环境的问题。
便携包在python_embeded下打开CMD，输入python -m pip show diffusers
看是否有
如果没有输入python -m pip install diffusers
或者版本太低，输入 python -m pip install -U diffusers

**Comment by ak3389** [comment]
I have the same problem, I'm using the desktop version.
