### ISSUE TITLE
DLL load failed while importing _framework_bindings: 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by jvavtom** [smthemex/ComfyUI_EchoMimic#98]
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_EchoMimic\__init__.py", line 2, in <module>
    from .EchoMimic_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 21, in <module>
    from .src.utils.draw_utils import FaceMeshVisualizer
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\utils\draw_utils.py", line 2, in <module>
    import mediapipe as mp
  File "D:\ComfyUI\python_embeded\Lib\site-packages\mediapipe\__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "D:\ComfyUI\python_embeded\Lib\site-packages\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import model_ckpt_util
ImportError: DLL load failed while importing _framework_bindings: 动态链接库(DLL)初始化例程失败。

Cannot import D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_EchoMimic module for custom nodes: DLL load failed while importing _framework_bindings: 动态链接库(DLL)初始化例程失败。

**Comment by smthemex** [comment]
重新安装 mediapipe 试试，你这个问题还是第一次看到

**Comment by wangzf657** [comment]
pip install msvc-runtime

**Comment by zdjzce** [comment]
I advise you to install this. It works for me. https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
